/* Shared guard for the C parity suites.
 *
 * Every suite reads a generated TSV and reports "<pass>/<total> C <name> parity". Rows
 * without a tab are skipped, and nothing checked the total — so an emptied or truncated
 * corpus printed "0/0 ... parity" and EXITED 0: the oracle silently checking nothing,
 * which is the one failure mode these suites exist to prevent. Each suite now declares
 * how many rows its corpus must have. Mirrors the `assert len(rows) == 69` guard in
 * tests/test_ssml_primitives.py.
 *
 * The counts are generated by scripts/emit_c_data.py; update them together.
 */
#ifndef CY_TEST_COMMON_H
#define CY_TEST_COMMON_H

#include <stdio.h>

/* 0 if the corpus is the expected size, else 1 (and says so). Add to the suite's
 * failure count so the process exits non-zero. */
static int check_count(const char *name, int total, int expect) {
    if (total == expect) return 0;
    printf("  FAIL %s corpus has %d rows, expected %d "
           "(regenerate with scripts/emit_c_data.py, or update the expected count)\n",
           name, total, expect);
    return 1;
}

#endif /* CY_TEST_COMMON_H */
